# -*- coding: utf-8 -*-
"""Read Lines

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w-qLMbC803wU81naXTpCrDck3KgNsNfV
"""

pip install simalign

from simalign import SentenceAligner

# making an instance of our model.
# You can specify the embedding model and all alignment settings in the constructor.
myaligner = SentenceAligner(model="bert", token_type="bpe", matching_methods="m")

lines1 = []
lines2 = []
with open('test1 eng.txt') as eng1, open('test1 per.txt') as per1:
    lines1 = eng1.readlines()
    lines2 = per1.readlines()

for (x1, x2) in zip(lines1, lines2):
    a = x1
    b = x2
    mehrdadalignment = myaligner.get_word_aligns(a, b)
    print(mehrdadalignment)
    with open('res.txt', 'a') as f:
      f.write('{}'.format(myaligner.get_word_aligns(a, b)))
      f.write('\n')
f.close()